version: '3.8'

services:
  postgres:
    image: db
    container_name: db
    build:
      context: ./db
      target: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5555:5432

  postgres_test:
    image: db
    container_name: test_db
    build:
      context: ./db
      target: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER_TEST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST}
      - POSTGRES_DB=${POSTGRES_DB_TEST}
    ports:
      - 5566:5432
